# yml -> yaml(야믈) / JSON에서 괄호를 제거한 것
language: java
jdk:
  - openjdk8
# branches - Travis CI를 어느 브랜치가 푸시될때 수행할지 지정
branches:
  only:
    - master

# Travis CI 서버의 Home
# cache - 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉 토리에  캐시하여 같은 의존성은 다음 배포때부터
# 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 빌드시 권한이 없어 오류 발생을 막기위한 권한 추가
before_install:
  - chmod +x gradlew

# script - master 브랜치에 푸시되었을때 수행하는 명령어 , gradlew를 통해 clean & build 수행
script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - alfkwl1239@naver.com